--- 
title: "Taller de R aplicado a la demografía"
author: "Ayelén Martinez, Florencia Bathory e Iván Williams"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Este espacio contiene..."
---

# Introducción

## Información general

Este sitio web contiene los materiales para el taller ofrecido en la Universidad Nacional de Luján, bajo el programa de maestría y especialización en Demografía Social, durante noviembre y diciembre de 2023. **No** es una guía autoexplicada, sino un acompañamiento para y soporte para la cursada. 

Algunas cosas útiles:

- El programa actualizado se puede encontrar aquí: https://github.com/IvanWilli/TallerDemoR/blob/master/programa/Programa.pdf.
- Encuentra el código fuente de este sitio web en GitHub: https://github.com/IvanWilli/TallerDemoR/blob/master/docs/index.Rmd.
- Los datos para los ejercicios se pueden encontrar en: https://github.com/IvanWilli/TallerDemoR/tree/master/docs/data.
- Los encuentros virtuales los haremos vía zoom en este [link](https://us02web.zoom.us/j/87912678557).

Ten en cuenta que esta página puede *cambiar* durante el curso, así que no te preocupes si notas algunos cambios. Podemos adaptar el contenido en función de la interacción que vayamos teniendo o corregir/agregare código a lo largo del camino.

Esperamos que disfrutes el taller y te sea útil.

Ayelén, Florencia e Iván

<!-- --------------------------------------------------------------------- -->

## PrepaRándonos

Estimad@,

Pronto comenzaremos el **Taller de R aplicado a la Demografía**. El objetivo es que puedas dar tus primeros pasos en la herramienta y puedas aplicar allí las principales técnicas de la demografía.

Esta edición del taller (tercera en su historia) la realizaremos un poco presencial (primer y último encuentro al menos) y un poco virtual. Para nuestro primer día sería bueno llevar lista tu compu en lo que atañe a la instalación del programa, de los paquetes y otras cuestiones mínimas, que si bien vamos a poder ayudarte in situ, nos ahorraría tiempo para comenzar con los materiales.

Te proponemos tomarte unos minutos para que podamos arrancar sin problemas la primera clase. No te frustres si algo no funciona, podés contactárnos para ir solucionándolo. 

### Instalación de y RStudio

Si estuviéramos en un auto, *R* es el motor, el sistema de dirección y frenos, y **RStudio** es nuestra interfaz: volante, pedales y los botoncitos que tocamos en los paneles (por ejemplo para poner ASPEN en la radio y disfrutar del viaje). Necesitamos instalar ambos y en su última versión disponible. 

Para esto debés ingresar a la página de descarga de [R](http://mirror.fcaglp.unlp.edu.ar/CRAN/), e ir al instalador según el sistema operativo que utilices, la versión escritorio (*desktop*). Ejecuta el *.exe* y sigue los pasos. Como chequeo, la última versión es la **4.3.1**. Luego debes ir a la web de [RStudio](https://www.rstudio.com/products/rstudio/download/) y repetir el proceso previo. Un video muy ilustrativo del proceso de instalación es [este](https://www.youtube.com/watch?v=Nmu4WPdJBRo)^[A lo largo de este taller nos valdremos de contenido realizado por muuuchas personas. Una práctica que nos gustaría contagiarte: si nos aporta, démosle *like* y/o compartamos y/o dejémos algún feedback si es posible].

Para aquellos que ya tienen *R* instalado pero de una versión previa, pueden volver a instalarlo siguiendo los pasos previos, que RStudio tomará de inmediato la más reciente cuando inicie una nueva sesión. O también pueden utilizar el paquete `installr` para los que ya vienen más habitué (sí, [existe](https://www.asale.org/damer/habitu%C3%A9)).

### Instalación de paquetes

Los paquetes (**packages** en inglés) son repositorios de código que contienen funciones relacionadas. Cada paquete tiene un tema al que se dedica, y dentro de éste, un objetivo o múltiples, siempre interrelacionados. A lo largo del taller utilizaremos muchos, por eso sería deseable que tengas instalados previamente algunos, ya que el éxitoen parte depende de que la conexión a internet funcione bien. Abrí **RStudio** y en la consola pega el siguiente código, luego ejecutalo. Te arrojará un montón de mensajes sobre el proceso de instalación pero con suerte el último deberá darte un ok.

```{r, eval=FALSE}
install.packages(c("tidyverse", "devtools", "foreign", "eph", "plotly", "gapminder", "gridExtra", "wpp2019", "HMDHFDplus","rgdal","spdplyr","leaflet"))
```

### Foro 

Para comunicarnos durante la semana y que haya un intercambio fluido utilizaremos el apartado de [issues](https://github.com/IvanWilli/TallerDemoR/issues) del repositorio en githug, que permite escribir incluyendo pedazos de código (el lenguaje es markdown, que veremos en la última unidad). Para esto te debes crearte un usuario. El uso de este espacio es **opcional**: si bien será útil para discutir contenido en la semana, si hay comunicaciones importantes de tipo administrativo se harán por mail.

### Por último 

Si estás sin tiempo, lo **prioritario** es la instalación previa de *R* y *RStudio*. Cualquier cosa nos podés contactar por mail:

- Iván Williams: act.ivanwilliams@gmail.com

- Ayelén Martinez: ayemartinezn@gmail.com

- Florencia Bathory: florencia.bathory@gmail.com

Recordá que en los encuentros virtuales lo haremos vía Zoom en en este [link](https://us02web.zoom.us/j/87912678557).

<!-- --------------------------------------------------------------------- -->

## Introducción

Como introducción, charlaremos en base a los slides de [aquí](https://github.com/IvanWilli/TallerDemoR/blob/master/ppt/Introduccion.html).
